# Generated by Django 2.1.2 on 2018-10-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_auto_20181019_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='iteration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=50),
        ),
    ]
